id: P007973
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG13808
  title: འཁྲིག་གཏམ་དམར་རྗེན་མ།
  author: ''
  volumes:
    974da088674944c8974a108fb4a4a41b:
      image_group_id: I1KG15780
      title: Volume 1 of 'khrig gtam dmar rjen ma/
      volume_number: 1
      total_pages: 164
      base_file: v001.txt
