id: P007973
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13808
  title: འཁྲིག་གཏམ་དམར་རྗེན་མ།
  author: ''
  volumes:
    a6621b74c040417eb447c7616d5f99d7:
      image_group_id: I1KG15780
      title: ''
      volume_number: 1
      total_pages: 164
ebook_metadata:
  title: འཁྲིག་གཏམ་དམར་རྗེན་མ།
  author: ''
  sku: P007973
  cover: cover.jpg
  layers:
  - pagination
