id: opecha:P007973
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13808
  title: འཁྲིག་གཏམ་དམར་རྗེན་མ།
  volume:
    974da088674944c8974a108fb4a4a41b:
      image_group_id: I1KG15780
      title: Volume 1 of 'khrig gtam dmar rjen ma/
      volume_number: 1
      total_pages: 164
  author: ''
ebook_metadata:
  title: འཁྲིག་གཏམ་དམར་རྗེན་མ།
  author: ''
  sku: P007973
  cover: cover.jpg
  layers:
  - pagination
