id: IC53FFCDD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:12:26+00:00'
last_modified: '2022-06-09T08:10:44.786740+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13808
  title: འཁྲིག་གཏམ་དམར་རྗེན་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9F42:
      image_group_id: I1KG15780
      title: Volume 1 of 'khrig gtam dmar rjen ma/
      total_pages: 164
      order: 1
      base_file: 9F42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
